version: '1'

services:
  nginx:
    image: nginx:latest
    container_name: webserver.1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443    
    volumes:
      - /home/ubuntu/personalweb/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/personalweb:/usr/share/nginx/html/