jobs:
  enviar_correo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Necesario para acceder a git si usas comandos git

      - name: Obtener Mensaje del Commit
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "::set-output name=mensaje::$COMMIT_MESSAGE"
        id: get_message # Asigna un ID a este paso para referenciar su output

      - name: Mostrar mensaje del commit (opcional)
        run: echo "El mensaje del commit es: ${{ steps.get_message.outputs.mensaje }}"
