name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           echo "${{ secrets.DOCKERPW }}" | docker login -u "croguerrero" --password-stdin
           docker build . --file build/Dockerfile --tag croguerrero/webpage:$(date +%s)
           docker push croguerrero/webpage:$(date +%s)
